# Site settings
title: James Lemin
description: > # this means to ignore newlines until "baseurl:"
  The personal site of James Lemin
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://james-lemin.com" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
