# Site settings
title: James Lemin
email: james@james-lemin.com
description: > # this means to ignore newlines until "baseurl:"
  The personal site of James Lemin
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://james-lemin.com" # the base hostname & protocol for your site
twitter_username: jasmine_elm
github_username:  jasmineelm

# Build settings
markdown: kramdown
